name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  Local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - name: Stubbed-Functional
        run: |
          make local-stubbed-functional
      - name: Stubbed-NFT
        run: |
          make local-stubbed-nft
